interface ZIF_KRAM_BASE_GUI_TRANSACTIONS
  public .


  class-methods CALL_TRANSACTION_01
    importing
      !IV_TRANSACTION_CODE type ZKRAM_TRANSACTION_CODE
      !IV_SKIP_FIRST_SCREEN_X type ABAP_BOOL default ZCL_KRAM_BASE_CONSTANTS=>TRUE
      !IT_SET_GET_PARAMETERS type ZKRAM_TT_SET_GET_PARAMETERS optional
    raising
      ZCX_KRAM_BASE_GUI .
  class-methods CALL_TRANSACTION_02
    importing
      !IV_TRANSACTION_CODE type ZKRAM_TRANSACTION_CODE
      !IT_SET_GET_PARAMETERS type ZKRAM_TT_SET_GET_PARAMETERS optional
      !IT_BATCH_INPUT type ZKRAM_TT_BATCH_INPUT
    exporting
      !ET_BATCH_INPUT_MESSAGES type ZKRAM_TT_BATCH_INPUT_MESSAGES
    raising
      ZCX_KRAM_BASE_GUI .
endinterface.
